import { type LevelData, NORTH, EAST, SOUTH, WEST } from "./types";

export const levels: LevelData[] = [
  // === World 1: Meadow Start ===
  {
    id: "1-1",
    worldId: 1,
    levelIndex: 0,
    name: "First Steps",
    width: 6,
    height: 6,
    start: { row: 2, col: 1, direction: EAST },
    goal: { row: 2, col: 3 },
    obstacles: [],
    inventory: { straight: 1, curve: 0 },
    par: 1,
    biome: "meadow",
    hint: "Place a straight tile to connect the path!",
  },
  {
    id: "1-2",
    worldId: 1,
    levelIndex: 1,
    name: "A Little Further",
    width: 6,
    height: 6,
    start: { row: 2, col: 0, direction: EAST },
    goal: { row: 2, col: 4 },
    obstacles: [],
    inventory: { straight: 3, curve: 0 },
    par: 3,
    biome: "meadow",
    hint: "Line up straight tiles to reach the gold!",
  },
  {
    id: "1-3",
    worldId: 1,
    levelIndex: 2,
    name: "First Turn",
    width: 6,
    height: 6,
    start: { row: 3, col: 1, direction: EAST },
    goal: { row: 1, col: 3 },
    obstacles: [],
    inventory: { straight: 2, curve: 1 },
    par: 3,
    biome: "meadow",
    hint: "Use a curve tile to change Lucky's direction! Click it again to rotate.",
  },
  {
    id: "1-4",
    worldId: 1,
    levelIndex: 3,
    name: "Right This Way",
    width: 6,
    height: 6,
    start: { row: 1, col: 1, direction: EAST },
    goal: { row: 3, col: 3 },
    obstacles: [],
    inventory: { straight: 2, curve: 1 },
    par: 3,
    biome: "meadow",
    hint: "Rotate the curve to turn Lucky the other way!",
  },
  {
    id: "1-5",
    worldId: 1,
    levelIndex: 4,
    name: "The L-Bend",
    width: 6,
    height: 6,
    start: { row: 3, col: 1, direction: NORTH },
    goal: { row: 1, col: 3 },
    obstacles: [],
    inventory: { straight: 2, curve: 1 },
    par: 3,
    biome: "meadow",
  },
  {
    id: "1-6",
    worldId: 1,
    levelIndex: 5,
    name: "Zigzag",
    width: 6,
    height: 6,
    start: { row: 3, col: 0, direction: EAST },
    goal: { row: 1, col: 3 },
    obstacles: [],
    inventory: { straight: 2, curve: 2 },
    par: 4,
    biome: "meadow",
  },
  {
    id: "1-7",
    worldId: 1,
    levelIndex: 6,
    name: "Rocky Road",
    width: 6,
    height: 6,
    start: { row: 3, col: 0, direction: EAST },
    goal: { row: 1, col: 4 },
    obstacles: [{ row: 2, col: 2 }],
    inventory: { straight: 3, curve: 2 },
    par: 5,
    biome: "meadow",
  },
  {
    id: "1-8",
    worldId: 1,
    levelIndex: 7,
    name: "Meadow's End",
    width: 6,
    height: 6,
    start: { row: 4, col: 0, direction: EAST },
    goal: { row: 0, col: 5 },
    obstacles: [{ row: 2, col: 2 }, { row: 3, col: 4 }],
    inventory: { straight: 4, curve: 4 },
    par: 8,
    biome: "meadow",
  },
  // === World 2: Mushroom Maze ===
  {
    id: "2-1",
    worldId: 2,
    levelIndex: 0,
    name: "Spore Path",
    width: 6,
    height: 6,
    start: { row: 0, col: 0, direction: SOUTH },
    goal: { row: 3, col: 3 },
    obstacles: [{ row: 2, col: 1 }],
    inventory: { straight: 3, curve: 2 },
    par: 5,
    biome: "mushroom",
  },
  {
    id: "2-2",
    worldId: 2,
    levelIndex: 1,
    name: "Fungal Twist",
    width: 7,
    height: 7,
    start: { row: 3, col: 0, direction: EAST },
    goal: { row: 3, col: 6 },
    obstacles: [{ row: 3, col: 3 }],
    inventory: { straight: 3, curve: 4 },
    par: 7,
    biome: "mushroom",
  },
  {
    id: "2-3",
    worldId: 2,
    levelIndex: 2,
    name: "Cap and Stem",
    width: 7,
    height: 7,
    start: { row: 5, col: 1, direction: NORTH },
    goal: { row: 1, col: 5 },
    obstacles: [{ row: 3, col: 3 }],
    inventory: { straight: 5, curve: 2 },
    par: 7,
    biome: "mushroom",
  },
  {
    id: "2-4",
    worldId: 2,
    levelIndex: 3,
    name: "Mycelium Network",
    width: 7,
    height: 7,
    start: { row: 0, col: 3, direction: SOUTH },
    goal: { row: 6, col: 3 },
    obstacles: [{ row: 2, col: 3 }],
    inventory: { straight: 4, curve: 4 },
    par: 7,
    biome: "mushroom",
  },
];

export function getLevelById(id: string): LevelData | undefined {
  return levels.find((l) => l.id === id);
}

export function getLevelsForWorld(worldId: number): LevelData[] {
  return levels.filter((l) => l.worldId === worldId);
}

export const worlds = [
  { id: 1, name: "Meadow Start", biome: "meadow" as const, color: "#4ade80" },
  { id: 2, name: "Mushroom Maze", biome: "mushroom" as const, color: "#c084fc" },
  { id: 3, name: "Rainbow Run", biome: "rainbow" as const, color: "#60a5fa" },
  { id: 4, name: "Gold Grove", biome: "grove" as const, color: "#fbbf24" },
];
